namespace EquipmentEvolved.Assets.CharmsModule;

public enum CharmName
{
    NotInitialized = 0,
    WhisperingBreeze = 1,
    DappledLeaf = 2,
    GlimmeringPebble = 3,
    FadedStar = 4,
    GentleWave = 5,
    RustyKey = 6,
    HiddenBlossom = 7,
    RustyNail = 8,
    WanderingCloud = 9,
    DustyJournal = 10,

    CrystalShard = 11,
    SteelEmblem = 12,
    CrystalPrism = 13,
    OnyxRing = 14,
    EchoingLaughter = 15,
    AncientCoin = 16,
    MysticLantern = 17,
    ChasingShadows = 18,
    PolishedJade = 19,
    EnchantedQuill = 20,

    PhoenixTear = 21,
    EtherealWisp = 22,
    TimelessClock = 23,
    NebulaDust = 24,
    InfernalSpark = 25,
    RadiantTear = 26,
    EtherealEcho = 27,
    InfiniteCascade = 28,
    ShatteredDream = 29,
    LuminousHeart = 30,

    DragonsHeart = 31,
    EternalFlame = 32,
    VortexOfTime = 33,
    CelestialCrown = 34,
    ArcaneObelisk = 35,
    StarlightEssence = 36,
    ChosenRelic = 37,
    ShadowedGuardian = 38,
    ElementalSigil = 39,
    DimensionBreaker = 40,

    OrdersDecree = 41,
    Singularity = 42,
    SupernovaRemnant = 43,
    AstralNexus = 44,
    WhisperingInfinity = 45,
    SoulOfStars = 46,
    EtherealBlossom = 47,
    HeartOfTheCosmos = 48,
    CosmicDissonance = 49,
    CelestialSymphony = 50,
    
    OmniscientEye = 51,
    RealityWeaver = 52,
    DivineSpark = 53,
    InfiniteHorizon = 54,
    TimelessVoid = 55,
    FinalJudgment = 56,
    ArchangelsCore = 57,
    CosmicAuthority = 58,
    PrimordialTruth = 59,
    EternalDominion = 60,
}